apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: webasgi
  name: webasgi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webasgi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: webasgi
    spec:
      containers:
        - args:
            - daphne
            - -b
            - 0.0.0.0
            - -p
            - "8001"
            - dr_social_backend.asgi:application
          image: webasgi
          name: webasgi
          ports:
            - containerPort: 8001
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app
              name: webasgi-claim0
      restartPolicy: Always
      volumes:
        - name: webasgi-claim0
          persistentVolumeClaim:
            claimName: webasgi-claim0
status: {}
