apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: webapi
  name: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webapi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: webapi
    spec:
      containers:
        - args:
            - sh
            - /usr/src/app/setup.sh
          image: webapi
          name: webapi
          ports:
            - containerPort: 8000
          resources: {}
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - DAC_READ_SEARCH
            privileged: true
          volumeMounts:
            - mountPath: /usr/src/app
              name: webapi-claim0
      restartPolicy: Always
      volumes:
        - name: webapi-claim0
          persistentVolumeClaim:
            claimName: webapi-claim0
status: {}
